version: '3.8'
services:
  caddy:
    image: caddy:2.2.1-alpine
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/../caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  cityguessr-service:
    image: thtsbe/cityguessr-service:latest
    container_name: cityguessr_service
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
  cityguessr-app:
    image: thtsbe/cityguessr-app:latest
    container_name: cityguessr_app
    restart: always
  mongodb:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONG_INITDB_DATABASE: cityguessr
  mongodb-test:
    image: mongo
    container_name: mongo_db_test
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONG_INITDB_DATABASE: cityguessr
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
  mongo-express-test:
    image: mongo-express
    container_name: mongo_express_test
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-test
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
volumes:
  caddy_data:
  caddy_config:
